### ISSUE TITLE
Use Mike's new data for simulator input

### ISSUE THREAD

**Issue by akinnear** [akinnear/tspi-message-project#22]
Mike has relevant data for use in the simulator use it.

**Comment by caseyshields** [comment]
Wrote a broadcaster which sends the Observations from a simulation over UDP, using MessagePlayback as an example. Still need to decide on how to format the observations, and make corresponding changes on the receive side.

**Comment by caseyshields** [comment]
I made it just produce csv lines for now since I don't yet have the Sids format. Though I did change the format, removing the truth, and making a message come from each pedestal.
I'm not sure how to test it against the listening service right now.
